### PR TITLE
French translation fixes

### PR DESCRIPTION
**Pull request by fthiery**

### CODE REVIEW

**Comment by stefansaraev** [comment]
translations are done via transiflex

**Comment by fthiery** [comment]
Hi

Am i supposed to go here ? https://www.transifex.com/projects/p/openelec-addons/language/fr/ I don't really find the strings i fixed (what are the audo and SickPotatoHead files ?)

**Comment by stefansaraev** [comment]
here it is https://www.transifex.com/projects/p/xbmc-addons/resource/service-openelec-settings/

**Comment by fthiery** [comment]
Done, thanx. It would be nice to find the information on http://openelec.tv/donate !

**Pull request closed without merging**
